name: Add mask
on: workflow_dispatch
jobs:
  log:
    runs-on: ubuntu-latest
    env:
      PASSWORD: SuoerSecretValue
    steps:
      - run: echo "::add-mask::${PASSWORD}"
      - run: echo "${PASSWORD}"